version: '3'
services:
    web:
        restart: always
        build: ./web
        expose:
            - "8000"
        volumes:
            - ./web:/vol
        environment:
            - REDIS_URL=redis://redis:6379
        command: /bin/bash -c "/usr/local/bin/gunicorn --worker-class eventlet -w 2 -b 0.0.0.0:8000 sknightmare.flask_app:app & celery -A sknightmare.flask_app.celery worker --concurrency=2 --loglevel=info"

    redis:
        restart: always
        image: redis:latest
        volumes:
            - ./redis_data:/data
        command: redis-server
        expose:
            - "6379"

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        volumes: 
            - ./sknightmare/static:/www/static


