version: '2.0'
services:
  web:
    build: .
    ports: 
      - 5000:5000
    environment:
      - REDIS_URL=redis://redis:6379
  redis:
    image: redis
  celeryd:
    build: .
    working_dir: /app/sknightmare 
    environment:
      - REDIS_URL=redis://redis:6379
    command: celery -A flask_app.celery worker --loglevel=INFO